pipeline {
    agent any
    stages {
        stage('Build and push Docker image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-hub', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                    sh 'packer init ./docker/packer_config.pkr.hcl'
                    sh "packer build --var docker_username=$DOCKER_USERNAME --var docker_password=$DOCKER_PASSWORD ./docker/packer_config.pkr.hcl"
                }
            }
        }
        stage('Run on Kubernetes') {
            steps {
                sh 'kubectl apply -f ./kubernetes/'
            }
        }
    }
}