apiVersion: v1
kind: Service
metadata:
  name: go-calculator-service
  labels:
    app: go-calculator
    project: tema18-devops
spec:
  type: LoadBalancer
  selector:
    app: go-calculator
    project: tema18-devops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080